[project]
name = "python-plc-visualizer"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.10"
dependencies = [
    "parse>=1.20.2",
    "pyside6>=6.6",
    "pytest>=8.4.2",
    "pytest-qt>=4.5.0",
    "pyyaml>=6.0",
    "qt-material>=2.17",
]
